---
- name: Install necessary dependencies
  ansible.builtin.apt:
    name: "{{ vector_dependencies }}"
    state: present
    update_cache: yes

- name: Create a virtual environment for Vector
  ansible.builtin.command:
    cmd: python3 -m venv {{ vector_venv_path }}
  args:
    creates: "{{ vector_venv_path }}/bin/activate"
